name = "BoteSalvatICX"
uuid = "fe54227b-96c7-489b-9963-dd1ce2905f30"
authors = ["Nicholas W. M. Ritchie <nicholas.ritchie@nist.gov>"]
repo-url = "https://github.com/usnistgov/BoteSalvatICX.jl"
version = "2.0.2"

[deps]
Requires = "ae029012-a4dd-5104-9daa-d747884805df"

[compat]
Gadfly = "1.3"
Requires = "1"
Weave = "0.10"
julia = "1"

[extras]
Gadfly = "c91e804a-d5a3-530f-b6f0-dfbca275c004"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Weave = "44d3d7a6-8a23-5bf8-98c5-b353f8df5ec9"

[targets]
test = ["Test"]
